kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    scheduler:
      extraArgs:
        v: "3"
    controllerManager:
      extraArgs:
        v: "3"
        concurrent-gc-syncs: "100"
        kube-api-qps: "100"
        kube-api-burst: "200"
    etcd:
      local:
        dataDir: /tmp/k8s-etcd-data
    apiServer:
      extraArgs:
        enable-aggregator-routing: "true"
        v: "3"
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "3"
- role: worker
  labels:
    instance-type: on-demand
- role: worker
  labels:
    instance-type: spot

kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "3"