/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EffectiveQuotaStatusApplyConfiguration represents a declarative configuration of the EffectiveQuotaStatus type for use
// with apply.
//
// EffectiveQuotaStatus denotes the effective quota structure used for scheduling.
type EffectiveQuotaStatusApplyConfiguration struct {
	// lastUpdateTime denotes the last update of the effective quota structure.
	LastUpdateTime *v1.Time `json:"lastUpdateTime,omitempty"`
	// capacityRevision denotes the manager's revision of the capacity used to infer the effective quota structure.
	CapacityRevision *int64 `json:"capacityRevision,omitempty"`
	// managerRef denotes the reference to the manager.
	ManagerRef *EffectiveQuotaStatusManagerRefApplyConfiguration `json:"managerRef,omitempty"`
	// resourceGroups denotes the effective quotas which, if present and feature gate is enabled,
	// should be used by scheduler for scheduling.
	ResourceGroups []ResourceGroupApplyConfiguration `json:"resourceGroups,omitempty"`
}

// EffectiveQuotaStatusApplyConfiguration constructs a declarative configuration of the EffectiveQuotaStatus type for use with
// apply.
func EffectiveQuotaStatus() *EffectiveQuotaStatusApplyConfiguration {
	return &EffectiveQuotaStatusApplyConfiguration{}
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *EffectiveQuotaStatusApplyConfiguration) WithLastUpdateTime(value v1.Time) *EffectiveQuotaStatusApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}

// WithCapacityRevision sets the CapacityRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapacityRevision field is set to the value of the last call.
func (b *EffectiveQuotaStatusApplyConfiguration) WithCapacityRevision(value int64) *EffectiveQuotaStatusApplyConfiguration {
	b.CapacityRevision = &value
	return b
}

// WithManagerRef sets the ManagerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagerRef field is set to the value of the last call.
func (b *EffectiveQuotaStatusApplyConfiguration) WithManagerRef(value *EffectiveQuotaStatusManagerRefApplyConfiguration) *EffectiveQuotaStatusApplyConfiguration {
	b.ManagerRef = value
	return b
}

// WithResourceGroups adds the given value to the ResourceGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceGroups field.
func (b *EffectiveQuotaStatusApplyConfiguration) WithResourceGroups(values ...*ResourceGroupApplyConfiguration) *EffectiveQuotaStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceGroups")
		}
		b.ResourceGroups = append(b.ResourceGroups, *values[i])
	}
	return b
}
